# Generated by Django 6.1.1 on 2026-09-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnerprofile',
            old_name='highlight_words',
            new_name='onboarding_complete',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='larger_text',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='more_spacing',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='pace',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='read_aloud',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='short_explanations',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='shorter_paragraphs',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='step_by_step',
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='explanation_depth',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='learning_style',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='reading_support',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
