# Generated by Django 6.1.1 on 2026-09-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_highlight_words_learnerprofile_onboarding_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerprofile',
            name='learning_style',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='reading_support',
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='examples',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='highlight_words',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='larger_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='listening_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='more_spacing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='pace',
            field=models.CharField(default='gentle', max_length=50),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='read_aloud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='short_explanations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='shorter_paragraphs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='step_by_step',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='explanation_depth',
            field=models.CharField(blank=True, choices=[('simple', 'Keep it simple'), ('breakdown', 'Break it down'), ('deep', 'Go deeper')], max_length=20),
        ),
    ]
